In [6]:
import io
import numpy as np
import pandas as pd

content = '''Trader     Buy/Sell   Profit
  A           1         1
  A           0         2
  B           1         3
  B           1         4
  B           0         5
  C           1         6
  C           0         7
  C           0         8'''

df = pd.read_table(io.BytesIO(content), sep='\s+')
df

  Trader  Buy/Sell  Profit
0      A         1       1
1      A         0       2
2      B         1       3
3      B         1       4
4      B         0       5
5      C         1       6
6      C         0       7
7      C         0       8

In [8]:
def isbuy(x):
    return x > 0

df['larger'] = df['Buy/Sell'].apply(isbuy)
df

  Trader  Buy/Sell  Profit larger
0      A         1       1   True
1      A         0       2  False
2      B         1       3   True
3      B         1       4   True
4      B         0       5  False
5      C         1       6   True
6      C         0       7  False
7      C         0       8  False